stages:
  - build
  - deploy

# build stage
build_app:
  image: node:14.14.0
  stage: build
  only:
    - master
  script:
    - echo -e $DOT_ENV >> .env
    - npm install
    - npm run build
  cache:
    paths:
      - node_modules/
  artifacts:
    paths:
      # build folder
      - dist/
    expire_in: 1 hour

Deploy to Prod:
  image: alpine:latest
  stage: deploy
  only:
    - master
  before_script:
    - apk update
    - apk add openssh
    - mkdir -p ~/.ssh
    - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh web1@10.255.22.193
    - bash deploy.sh

#
#  image:
#    name: amazon/aws-cli
#    entrypoint: [""]
#  stage: deploy
#  only:
#    - master
#  #when: manual
#  script:
#    - aws configure set region us-east-1
#    - aws s3 sync --acl public-read --delete dist/ s3://$S3_PROD_BUCKET
#    - aws cloudfront create-invalidation --distribution-id $PROD_DISTRIBUTION_ID --paths '/*'
